name: clonogenic
channels:
  - conda-forge
  - defaults
dependencies:
  - arviz=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2019.11.28
  - cctools=927.0.2
  - certifi=2019.11.28
  - cftime=1.1.1.1
  - clang=9.0.1
  - clang_osx-64=9.0.1
  - clangxx=9.0.1
  - clangxx_osx-64=9.0.1
  - compiler-rt=9.0.1
  - compiler-rt_osx-64=9.0.1
  - curl=7.68.0
  - cycler=0.10.0
  - freetype=2.10.1
  - h5py=2.10.0
  - hdf4=4.2.13
  - hdf5=1.10.5
  - jpeg=9c
  - kiwisolver=1.1.0
  - krb5=1.16.4
  - ld64=450.3
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.68.0
  - libcxx=9.0.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgfortran=4.0.0
  - libgpuarray=0.7.6
  - liblapack=3.8.0
  - libllvm9=9.0.1
  - libnetcdf=4.7.3
  - libopenblas=0.3.9
  - libpng=1.6.37
  - libssh2=1.8.2
  - llvm-openmp=9.0.1
  - mako=1.1.0
  - markupsafe=1.1.1
  - matplotlib=3.2.1
  - matplotlib-base=3.2.1
  - ncurses=6.1
  - netcdf4=1.5.3
  - numpy=1.18.1
  - openssl=1.1.1e
  - packaging=20.1
  - pandas=1.0.3
  - patsy=0.5.1
  - pip=20.0.2
  - pygpu=0.7.6
  - pymc3=3.8
  - pyparsing=2.4.6
  - python=3.8.2
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2019.3
  - readline=8.0
  - scipy=1.4.1
  - setuptools=46.1.1
  - six=1.14.0
  - sqlite=3.30.1
  - tapi=1000.10.8
  - theano=1.0.4
  - tk=8.6.10
  - tornado=6.0.4
  - tqdm=4.43.0
  - wheel=0.34.2
  - xarray=0.15.0
  - xz=5.2.4
  - zlib=1.2.11
prefix: /Users/evenhuis/anaconda3/envs/clonogenic
